export const writersXIX = [
  { id: "UKR330", name: "Poltavska", surname: "Ivan Kotliarevsky" },
  { id: "UKR330", name: "Poltavska", surname: "Yevhen Hrebinka" },
  { id: "UKR330", name: "Poltavska", surname: "Mykola Gogol" },
  { id: "UKR330", name: "Poltavska", surname: "Olena Pchilka" },
  { id: "UKR328", name: "Kharkivska", surname: "Hryhorii Kvitka-Osnovianenko" },
  { id: "UKR285", name: "Chernihivska", surname: "Panteleimon Kulish" },
  { id: "UKR285", name: "Chernihivska", surname: "Oleksa Storozhenko" },
  { id: "UKR319", name: "Cherkaska", surname: "Ivan Nechuy-Levytsky" },
  { id: "UKR319", name: "Cherkaska", surname: "Petro Hulak-Artemovskyi" },
  { id: "UKR319", name: "Cherkaska", surname: "Taras Shevchenko" },
  { id: "UKR319", name: "Cherkaska", surname: "Mykhailo Starytsky" },
  { id: "UKR323", name: "Vinnytska", surname: "Stepan Rudanskyi" },
  { id: "UKR323", name: "Vinnytska", surname: "Mykhailo Kotsiubynsky" },
  { id: "UKR324", name: "Zhytomyrska", surname: "Lesya Ukrainka" },
  { id: "UKR320", name: "Kirovohradska", surname: "Marko Kropyvnytskyi" },
  { id: "UKR320", name: "Kirovohradska", surname: "Ivan Karpenko-Karyi" },
  { id: "UKR288", name: "Chernivetska", surname: "Yuriy Fedkovych" },
  { id: "UKR291", name: "Lvivska", surname: "Ivan Franko" },
  { id: "UKR289", name: "Ivano-Frankivska", surname: "Marko Cheremshyna" },
];
