export const writersXXI = [
  { id: "UKR319", name: "Cherkaska", surname: "Irena Karpa" },
  { id: "UKR319", name: "Cherkaska", surname: "Vasyl Shkliar" },
  { id: "UKR319", name: "Cherkaska", surname: "Artem Chekh" },
  { id: "UKR285", name: "Chernihivska", surname: "Maria Matios" },
  { id: "UKR289", name: "Ivano-Frankivska", surname: "Yurii Andrukhovych" },
  { id: "UKR289", name: "Ivano-Frankivska", surname: "Oleh Lysheha" },
  { id: "UKR289", name: "Ivano-Frankivska", surname: "Yuriy Izdryk" },
  { id: "UKR289", name: "Ivano-Frankivska", surname: "Taras Prokhasko" },
  { id: "UKR289", name: "Ivano-Frankivska", surname: "Yuriy Vynnychuk" },
  { id: "UKR327", name: "Donetska", surname: "Irene Rozdobudko" },
  { id: "UKR329", name: "Luhanska", surname: "Serhiy Zhadan" },
  { id: "UKR291", name: "Lvivska", surname: "Oleksandr Irvanets" },
  { id: "UKR291", name: "Lvivska", surname: "Marianna Kiyanovska" },
  { id: "UKR291", name: "Lvivska", surname: "Stepan Protsiuk" },
  { id: "UKR291", name: "Lvivska", surname: "Natalka Sniadanko" },
  { id: "UKR291", name: "Lvivska", surname: "Lubko Deresh" },
  { id: "UKR318", name: "Volynska", surname: "Oksana Zabuzhko" },
  { id: "UKR293", name: "Zakarpatska", surname: "Andriy Lyubka" },
  { id: "UKR4826", name: "Kyiv City", surname: "Oleksandr Mykhed" },
  { id: "UKR324", name: "Zhytomyrska", surname: "Valeriy Shevchuk" },
  { id: "UKR4826", name: "Kyiv City", surname: "Les Podervianskyi" },
  { id: "UKR4827", name: "Khersonska", surname: "Lyuko Dashvar" },
];
