export const writerspre = [
  { id: "UKR289", name: "Ivano-Frankivska", surname: "Pamvo Berynda" },
  { id: "UKR330", name: "Poltavska", surname: "Samiilo Velychko" },
  { id: "UKR330", name: "Poltavska", surname: "Hryhorii Skovoroda" },
  { id: "UKR330", name: "Poltavska", surname: "Mykola Khanenko" },
  { id: "UKR291", name: "Lvivska", surname: "Ivan Vyshenskyi" },
  { id: "UKR291", name: "Lvivska", surname: "Lavrentiy Zyzanii" },
  { id: "UKR291", name: "Lvivska", surname: "Cassian Sakowicz" },
  { id: "UKR321", name: "Kyivska", surname: "Volodymyr Monomakh" },
  { id: "UKR321", name: "Kyivska", surname: "Vasil Grigorovich-Barsky" },
  { id: "UKR321", name: "Kyivska", surname: "Ivan Nekrashevych" },
  { id: "UKR321", name: "Kyivska", surname: "Demetrius Tuptalo" },
  { id: "UKR321", name: "Kyivska", surname: "Theodosius of the Caves" },
  { id: "UKR318", name: "Volynska", surname: "Ioanikiy Halyatovskyi" },
  { id: "UKR285", name: "Chernihivska", surname: "Yakov Markovych" },
  { id: "UKR290", name: "Khmelnytska", surname: "Herasym Smotrytsky" },
  { id: "UKR290", name: "Khmelnytska", surname: "Meletius Smotrytsky" },
  { id: "UKR286", name: "Rivnenska", surname: "Kyrylo Stavrovetsky" },
  { id: "UKR318", name: "Volynska", surname: "Christophor Philaleth" },
];
