export const writersXX = [
  { id: "UKR285", name: "Chernihivska", surname: "Pavlo Tychyna" },
  { id: "UKR285", name: "Chernihivska", surname: "Mykhailo Kotsiubynsky" },
  { id: "UKR285", name: "Chernihivska", surname: "Oleksandr Dovzhenko" },
  { id: "UKR327", name: "Donetska", surname: "Emma Andijewska" },
  { id: "UKR327", name: "Donetska", surname: "Volodymyr Sosiura" },
  { id: "UKR327", name: "Donetska", surname: "Ivan Dzyuba" },

  { id: "UKR320", name: "Kirovohradska", surname: "Volodymyr Vynnychenko" },
  { id: "UKR290", name: "Khmelnytska", surname: "Yury Klen" },
  { id: "UKR320", name: "Kirovohradska", surname: "Yury Yanovskyi" },
  { id: "UKR320", name: "Kirovohradska", surname: "Evgen Malanyuk" },
  { id: "UKR289", name: "Ivano-Frankivska", surname: "Vasyl Stefanyk" },
  { id: "UKR289", name: "Ivano-Frankivska", surname: "Ivan Malkovych" },

  { id: "UKR326", name: "Dnipropetrovska", surname: "Valerian Pidmohylny" },
  { id: "UKR326", name: "Dnipropetrovska", surname: "Viktor Petrov" },
  { id: "UKR326", name: "Dnipropetrovska", surname: "Oles Honchar" },
  { id: "UKR328", name: "Kharkivska", surname: "Mike Johansen" },
  { id: "UKR328", name: "Kharkivska", surname: "Boris Oliynyk" },
  { id: "UKR328", name: "Kharkivska", surname: "Oleksandr Oles" },
  { id: "UKR328", name: "Kharkivska", surname: "Ivan Bahrianyi" },
  { id: "UKR328", name: "Kharkivska", surname: "Yury Shevelyov" },
  { id: "UKR286", name: "Rivnenska", surname: "Ulas Samchuk" },

  { id: "UKR4827", name: "Khersonska", surname: "Vasyl Sukhomlynsky" },
  { id: "UKR4827", name: "Khersonska", surname: "Mykola Kulish" },
  { id: "UKR290", name: "Khmelnytska", surname: "Mykola Bazhan" },
  { id: "UKR290", name: "Khmelnytska", surname: "Ihor Rymaruk" },
  { id: "UKR325", name: "Sumska", surname: "Mykola Khvylovy" },
  { id: "UKR325", name: "Sumska", surname: "Boris Antonenko-Davydovych" },
  { id: "UKR325", name: "Sumska", surname: "Natalka BIlotserkivets" },

  { id: "UKR321", name: "Kyivska", surname: "Lina Kostenko" },
  { id: "UKR321", name: "Kyivska", surname: "Hryhoriy Kosinka" },
  { id: "UKR321", name: "Kyivska", surname: "Ivan Drach" },
  { id: "UKR321", name: "Kyivska", surname: "Andriy Malyshko" },
  { id: "UKR4826", name: "Kyiv City", surname: "Maxim Rylskyi" },
  { id: "UKR4826", name: "Kyiv City", surname: "Yaroslav Stelmakh" },
  { id: "UKR4826", name: "Kyiv City", surname: "Iryna Zhylenko" },
  { id: "UKR291", name: "Lvivska", surname: "Ivan Franko" },
  { id: "UKR291", name: "Lvivska", surname: "Ihor Kalynets" },

  { id: "UKR323", name: "Vinnytska", surname: "Vasyl Stus" },
  { id: "UKR318", name: "Volynska", surname: "Yuriy Kosach" },
  { id: "UKR330", name: "Poltavska", surname: "Hryhir Tiutiunnyk" },
  { id: "UKR330", name: "Poltavska", surname: "Vasyl Symonenko" },
  { id: "UKR330", name: "Poltavska", surname: "Pavlo Zahrebelnyi" },
  { id: "UKR330", name: "Poltavska", surname: "Mykola Zerov" },
  { id: "UKR330", name: "Poltavska", surname: "Vasyl Barka" },
  { id: "UKR330", name: "Poltavska", surname: "Mykhailo Semenko" },
  { id: "UKR324", name: "Zhytomyrska", surname: "Vsevolod Nestayko" },
  { id: "UKR324", name: "Zhytomyrska", surname: "Lesya Ukrainka" },
  { id: "UKR322", name: "Odeska", surname: "Mykola Vingranovskyi" },
  { id: "UKR329", name: "Luhanska", surname: "Vasyl Holoborodko" },
];
