export const allFinds = [
  { id: "UKR319", name: "Cherkaska" },
  { id: "UKR285", name: "Chernihivska" },
  { id: "UKR288", name: "Chernivetska" },
  { id: "UKR326", name: "Dnipropetrovska" },
  { id: "UKR327", name: "Donetska" },
  { id: "UKR289", name: "Ivano-Frankivska" },
  { id: "UKR328", name: "Kharkivska" },
  { id: "UKR4827", name: "Khersonska" },
  { id: "UKR290", name: "Khmelnytska" },
  { id: "UKR320", name: "Kirovohradska" },
  { id: "UKR321", name: "Kyivska" },
  { id: "UKR4826", name: "Kyiv City" },
  { id: "UKR329", name: "Luhanska" },
  { id: "UKR291", name: "Lvivska" },
  { id: "UKR284", name: "Mykolayivska" },
  { id: "UKR322", name: "Odeska" },
  { id: "UKR330", name: "Poltavska" },
  { id: "UKR286", name: "Rivnenska" },
  { id: "UKR325", name: "Sumska" },
  { id: "UKR292", name: "Ternopilska" },
  { id: "UKR323", name: "Vinnytska" },
  { id: "UKR318", name: "Volynska" },
  { id: "UKR293", name: "Zakarpatska" },
  { id: "UKR331", name: "Zaporizka" },
  { id: "UKR324", name: "Zhytomyrska" },
  { id: "UKR283", name: "Avtonomna Respublika Krym" },
  { id: "UKR5482", name: "Sevastopol" },
];
